package policy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	cedar "github.com/cedar-policy/cedar-go"
)

// This file wires Cedar (CNCF sandbox) in as the condition engine for
// `where` clauses (ADR 0002). Ordered matching (globs, tasks, expires)
// stays native; anything expression-shaped is real Cedar evaluated by
// cedar-go — we never invent our own expression language.
//
// The condition surface visible to policy authors:
//
//	context.tool        string   — the tool name
//	context.args        record   — the (redacted) tool arguments
//
// Example:  where: 'context.args.path like "/tmp/*"'

// conditionSet is one rule's `where` clauses compiled to a Cedar policy.
type conditionSet struct {
	policy *cedar.PolicySet
	exprs  []string
}

// compileWhere compiles a rule's where-clauses into a Cedar policy that
// permits only when every clause holds. nil (no clauses) always passes.
func compileWhere(ruleID string, where []string) (*conditionSet, error) {
	if len(where) == 0 {
		return nil, nil
	}
	src := fmt.Sprintf("permit(principal, action, resource) when { %s };", strings.Join(where, " && "))
	ps, err := cedar.NewPolicySetFromBytes("rule:"+ruleID, []byte(src))
	if err != nil {
		return nil, fmt.Errorf("rule %q: invalid where expression: %w", ruleID, err)
	}
	return &conditionSet{policy: ps, exprs: where}, nil
}

// passes evaluates the rule's conditions for a request. Evaluation errors
// fail closed (the rule does not apply).
func (c *conditionSet) passes(req Request) bool {
	if c == nil {
		return true
	}
	argsVal, err := jsonToCedarValue(req.Args)
	if err != nil {
		return false // fail closed: unconvertible arguments
	}
	ctx := cedar.NewRecord(cedar.RecordMap{
		cedar.String("tool"): cedar.String(req.Tool),
		cedar.String("args"): argsVal,
	})
	decision, diag := c.policy.IsAuthorized(cedar.EntityMap{}, cedar.Request{
		Principal: cedar.NewEntityUID("Tapelog", cedar.String("agent")),
		Action:    cedar.NewEntityUID("Tapelog", cedar.String("tool_call")),
		Resource:  cedar.NewEntityUID("Tapelog", cedar.String(req.Tool)),
		Context:   ctx,
	})
	if len(diag.Errors) > 0 {
		return false // fail closed on evaluation errors
	}
	return decision == cedar.Allow
}

// jsonToCedarValue converts a JSON value to a Cedar value.
// Objects become records, arrays become sets (order is not preserved),
// strings/bools/numbers map directly. JSON null is skipped in records
// (Cedar has no null).
func jsonToCedarValue(raw json.RawMessage) (cedar.Value, error) {
	if len(raw) == 0 {
		return cedar.NewRecord(cedar.RecordMap{}), nil
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	var v any
	if err := dec.Decode(&v); err != nil {
		return nil, fmt.Errorf("decode args: %w", err)
	}
	return toCedarValue(v)
}

func toCedarValue(v any) (cedar.Value, error) {
	switch t := v.(type) {
	case map[string]any:
		rec := cedar.RecordMap{}
		for k, val := range t {
			if val == nil {
				continue
			}
			cv, err := toCedarValue(val)
			if err != nil {
				return nil, err
			}
			rec[cedar.String(k)] = cv
		}
		return cedar.NewRecord(rec), nil
	case []any:
		vals := make([]cedar.Value, 0, len(t))
		for _, elem := range t {
			cv, err := toCedarValue(elem)
			if err != nil {
				return nil, err
			}
			vals = append(vals, cv)
		}
		return cedar.NewSet(vals...), nil
	case string:
		return cedar.String(t), nil
	case bool:
		return cedar.Boolean(t), nil
	case json.Number:
		if n, err := t.Int64(); err == nil {
			return cedar.Long(n), nil
		}
		f, err := t.Float64()
		if err != nil {
			return nil, fmt.Errorf("number %s: %w", t, err)
		}
		d, err := cedar.NewDecimalFromFloat(f)
		if err != nil {
			return nil, err
		}
		return d, nil
	default:
		return nil, fmt.Errorf("unsupported JSON value %T", v)
	}
}

// CompileCedar renders a YAML policy as portable Cedar policy text — for
// interop with Cedar-aware infrastructure (e.g. AGT/OPA-style gateways).
//
// Approximations (documented in docs/POLICY.md): YAML's ordered
// first-match-wins becomes Cedar effects (permit/forbid); `?` globs are
// widened to `*`; confirm rules export as permit with a comment.
func CompileCedar(p *Policy) string {
	var b strings.Builder
	b.WriteString("// Generated by `tapelog policy compile` (Cedar policy text).\n")
	b.WriteString("// Ordered first-match YAML semantics are approximated with effects;\n")
	b.WriteString("// `?` globs are widened to `*`.\n\n")
	for i := range p.Rules {
		r := &p.Rules[i]
		fmt.Fprintf(&b, "// action: %s", r.Action)
		if len(r.Tasks) > 0 {
			fmt.Fprintf(&b, "; tasks: %s", strings.Join(r.Tasks, ","))
		}
		if r.Expires != "" {
			fmt.Fprintf(&b, "; expires: %s", r.Expires)
		}
		if r.Action == string(VerdictConfirm) {
			b.WriteString(" (confirm exported as permit)")
		}
		b.WriteString("\n")

		kw := "permit"
		if r.Action == string(VerdictDeny) {
			kw = "forbid"
		}
		var conds []string
		if !(len(r.Tool) == 1 && r.Tool[0] == "*") {
			var likes []string
			for _, pat := range r.Tool {
				likes = append(likes, fmt.Sprintf("context.tool like %q", globToCedarLike(pat)))
			}
			conds = append(conds, "("+strings.Join(likes, " || ")+")")
		}
		for _, w := range r.Where {
			conds = append(conds, "("+w+")")
		}
		fmt.Fprintf(&b, "@id(%q)\n%s(principal, action, resource)", r.ID, kw)
		if len(conds) > 0 {
			fmt.Fprintf(&b, " when {\n  %s\n}", strings.Join(conds, " &&\n  "))
		}
		b.WriteString(";\n\n")
	}
	return b.String()
}

// globToCedarLike converts a tool glob to a Cedar `like` pattern
// (`?` is widened to `*`; Cedar has no single-char wildcard).
func globToCedarLike(pat string) string {
	return strings.ReplaceAll(pat, "?", "*")
}
